name: beehiveiot-localcontrollers-ci
on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
jobs:
  wait-for-previous-workflow-finished:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: "Block concurrent workflow executions"
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  set-unknown-state-badges-for-CI:
    runs-on: ubuntu-latest
    needs: wait-for-previous-workflow-finished
    steps:
      - name: "Create badge BuildDockerImage with unknown state"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 4bdea638e561aa2bdf13fad3c052a8e7
          filename: badgeBuildDockerImage.json
          label: Build
          message: unknown
          color: grey
  build-docker-image:
    runs-on: [self-hosted, MyDesktop]
    needs: set-unknown-state-badges-for-CI
    steps:
      - name: Checkout / clone GitHub repo
        uses: actions/checkout@main
        with:
          submodules: true
      - name: Build image from Dockerfile
        run: docker --log-level=debug build . --file=dockerimage/Dockerfile --tag nemuuser/rpi-pico-build-env:latest --rm=true
      - name: "Create badge BuildDockerImage with passing state"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 4bdea638e561aa2bdf13fad3c052a8e7
          filename: badgeBuildDockerImage.json
          label: Build
          message: passing
          color: green
      - name: "Create badge BuildDockerImage with failing state"
        if: ${{ failure() }}
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 4bdea638e561aa2bdf13fad3c052a8e7
          filename: badgeBuildDockerImage.json
          label: Build
          message: failing
          color: red
      - name: "Print existing docker images before cleanup the dangling ones"
        if: ${{ always() }}
        run: docker images --all
      - name: "Clean dangling docker images"
        if: ${{ always() }}
        run: docker rmi $(docker images -f "dangling=true" -q) || echo "No images to delete"
      - name: "Print existing docker images after cleanup the dangling ones"
        if: ${{ always() }}
        run: docker images --all
